PRUEBA NEAXIS/Models/ErrorViewModel.cs
namespace PRUEBA_NEAXIS.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PRUEBA NEAXIS/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PRUEBA_NEAXIS.Models;
using System.Diagnostics;

namespace PRUEBA_NEAXIS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PRUEBA NEAXIS/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PRUEBA_NEAXIS.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult Prueba()
        {
            return View();
        }
    }
}

PRUEBA NEAXIS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PRUEBA NEAXIS/Views/Prueba/Prueba.cshtml
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>JS Bin</title>
</head>
<body>
    <button class="btn lost" style=""  on-leave="Apagado" on-hover="Encendido" onclick="consumirservicio()" id="Button">Consumir</button>
    <script src="https://code.jquery.com/jquery-3.1.0.js"></script>
    <div class="row">
        <div class="col-md-12">
            <textarea type="text" id="users" name="users" size="200" rows="10" cols="80"></textarea>
        </div>
    </div>
</body>
</html>

<style>
    .btn {
        border-radius: 12px;
        padding: 2px;
  }

        .btn:focus {
            outline: none;
        }

        .btn.Apagado {
            background-color: #ffffff;
            border-radius: 12px;
            border: 2px solid #e97c14;
            color: #000000;
        }

        .btn.Encendido {
            background-color: #e97c14;
            border: 2px solid #e97c14;
            border-radius: 12px;
            color: #fff;
            box-shadow: 5px 5px 10px 2px rgba(0,0,0,.8);
        }
</style>

@section Scripts
{
<script type="text/javascript">
    $('.btn.lost').hover(onHover, onLeave);

    function onHover() {
        $(this).removeClass('Apagado');
        $(this).addClass('Encendido');
        $(this).text($(this).attr('on-hover'));
        $(this).text('Cancelar operación');
    }
    function onLeave() {
        $(this).removeClass('Encendido');
        $(this).addClass('Apagado');
        $(this).text($(this).attr('on-leave'));
        $(this).text('Cancelar operación');
    }


         function consumirservicio() {

        $.ajax({
            type: 'GET',
            url: 'https://api.github.com/users',
            dataType: 'json',
           success: function (result) { 
                for (var i=0; i<10; i++) {
                   $('#users').val($('#users').val()  + result[i].login + ',' + result[i].repos_url + ',' + result[i].type + "\n");
                 };
            },
            error: function (ex) {
                alert('Failed.' + ex);
            }
        });
    }


    const Button = document.getElementById('Button');
    Button.addEventListener('click', function () {
        Button.disabled = true;
        Button.style.opacity = 0.7;
        Button.textContent = 'Ejecutando proceso...';

        setTimeout(function () {
            Button.textContent = 'Apagado';
            Button.style.opacity = 1;
            Button.disabled = false;
        }, 5000);
    });
</script>
}

PRUEBA NEAXIS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PRUEBA_NEAXIS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PRUEBA_NEAXIS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PRUEBA_NEAXIS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prueba" asp-action="Prueba">Prueba</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PRUEBA_NEAXIS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>